name: 'Aliyun CDN Redirector Action Typescript'
description: 'Update the CDN redirect config'
author: 'VisionWX'
branding:
  icon: 'upload'
  color: 'gray-dark'
inputs:
  accessKeyId:
    description: 'Aliyun accessKeyId.'
    required: true
  accessKeySecret:
    description: 'Aliyun accessKeySecret.'
    required: true
  domain:
    description: 'CDN Domain,e.g. dw.xxx.com'
    required: true
  regex:
    description: 'The request path regex to match'
    required: true
  replacement:
    description: 'The redirect path'
    required: true
  configId:
    description: 'The redirect configId'
    required: true
runs:
  using: 'node16'
  main: 'dist/main.js'